# Generated by Django 2.2.6 on 2019-10-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('display', models.ImageField(default='groups/group.png', upload_to='groups/')),
                ('description', models.TextField(default='Random group')),
                ('police', models.TextField(default='999')),
                ('health', models.TextField(default='213')),
            ],
        ),
    ]
