# Generated by Django 2.2.6 on 2019-10-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0002_profile_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='neighborhood',
            new_name='neighbourhood',
        ),
    ]
