# Generated by Django 2.2.6 on 2019-10-31 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0003_auto_20191031_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='businesses',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood',
        ),
        migrations.AddField(
            model_name='businesses',
            name='bussiness_description',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='neighbourhood',
            field=models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myhood.Neighbourhood'),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhood.Profile'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='admin',
            field=models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
