# Generated by Django 2.2.6 on 2019-10-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0004_auto_20191031_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='neighbourhood',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhood.Neighbourhood'),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='user',
            field=models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myhood.Profile'),
        ),
    ]
